yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
npmScopes:
  artsalliancemedia:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "103db879-519f-47b6-92c8-c1a9af5d3b02"
packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
