nodeLinker: node-modules

npmScopes:
  artsalliancemedia:
    npmAuthToken: 0c0d2489-9bc9-4912-8469-4d9fe270e575
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
