nodeLinker: node-modules

npmScopes:
  artsalliancemedia:
    npmAuthToken: ${NPM_AUTH_TOKEN}
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
