apiVersion: apps/v1
kind: Deployment
metadata:
  name: screenwriter-online-frontend-nginx
spec:
  template:
    spec:
      containers:
        - name: screenwriter-online-frontend-nginx
          image: screenwriter-online-frontend-nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: screenwriter-online-frontend-nginx-configmap
      restartPolicy: Always
